[project]
name = "nobreak"
version = "0.1.0"
description = "analysis of AI algorithms for the stock exchange"
readme = "README.md"
authors = [
    { name = "Miguel", email = "migueldoiche2@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
nobreak = "nobreak:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
